### ISSUE TITLE
Notification id가 겹쳐 앱이 종료됨

### ISSUE THREAD

**Issue by DokySp** [noti-dropper/app-noti-spanner#1]
노티에 대한 id값을 조정할 필요가 있음.

**Comment by Dewey7171** [comment]
ID 값 때문에 오류는 아닌거 같음

**Comment by DokySp** [comment]
JSON 파싱 부분에서 발생하는 에러로 확인됨.

**Comment by DokySp** [comment]
commit [`16d5e77`](https://github.com/noti-dropper/app-noti-spanner/commit/16d5e7700290acfd8de3f2285db3e0dd1e472df6)에서 문제가 해결됨.
추후 원인을 찾아야 할듯.
